version: "3"
services:
  db:
    image: postgres:14
    container_name: supermarketdb
    environment:
      - POSTGRES_USER=supermarketdb
      - POSTGRES_PASSWORD=my-postgres-db-pwd
      - POSTGRES_DB=supermarketdb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data